// Mocks generated by Mockito 5.4.6 from annotations
// in shotgun_flutter/test/features/patch_applier/domain/usecases/apply_patch_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:shotgun_flutter/core/error/failures.dart' as _i5;
import 'package:shotgun_flutter/features/patch_applier/domain/entities/apply_result.dart'
    as _i6;
import 'package:shotgun_flutter/features/patch_applier/domain/entities/conflict.dart'
    as _i8;
import 'package:shotgun_flutter/features/patch_applier/domain/entities/patch.dart'
    as _i7;
import 'package:shotgun_flutter/features/patch_applier/domain/repositories/patch_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PatchRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPatchRepository extends _i1.Mock implements _i3.PatchRepository {
  MockPatchRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ApplyResult>> applyPatch(
    _i7.Patch? patch, {
    bool? dryRun = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#applyPatch, [patch], {#dryRun: dryRun}),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.ApplyResult>>.value(
                  _FakeEither_0<_i5.Failure, _i6.ApplyResult>(
                    this,
                    Invocation.method(#applyPatch, [patch], {#dryRun: dryRun}),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.ApplyResult>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i8.Conflict>>> detectConflicts(
    _i7.Patch? patch,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#detectConflicts, [patch]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i8.Conflict>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i8.Conflict>>(
                    this,
                    Invocation.method(#detectConflicts, [patch]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i8.Conflict>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i7.Patch>>> splitPatch(
    String? diff,
    int? lineLimit,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#splitPatch, [diff, lineLimit]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i7.Patch>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i7.Patch>>(
                    this,
                    Invocation.method(#splitPatch, [diff, lineLimit]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i7.Patch>>>);
}
