name: Flutter CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'shotgun_flutter/**'
      - '.github/workflows/flutter_ci.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'shotgun_flutter/**'
      - '.github/workflows/flutter_ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: shotgun_flutter
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Run code generation
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Analyze code
        run: flutter analyze

      - name: Run tests
        run: flutter test --coverage

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./shotgun_flutter/coverage/lcov.info
          flags: flutter
